UTC_OFFSET = 0  # Hours (e.g. 0 = UTC/GMT, 1 = CET)

DISPLAY_GPIO_PIN = 16
DISPLAY_ROWS = 8
DISPLAY_COLUMNS = 32
DISPLAY_FPS = 10
DISPLAY_ROTATION = 0
DISPLAY_BRIGHTNESS = 16  # / 255
DISPLAY_DEBUG = False
